ansible_user: admin
ansible_password: admin
ansible_network_os: cisco.nxos.nxos
ansible_connection: ansible.netcommon.network_cli
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa'

ospf:
  id: "1"
  area: "0"

bgp:
  asn: "65000"