# The base configuration for overlay leaf switches
# The rest of configuration is done in webhook_overlay.yml which triggered by NetBox
- name: Create VTEP
  cisco.nxos.nxos_interfaces:
    config:
      - name: "nve1"
        enabled: true

- name: Configure VTEP with BGP learning
  cisco.nxos.nxos_vxlan_vtep:
    interface: "nve1"
    host_reachability: true
    source_interface: "loopback0"
    shutdown: false