hostname: "Leaf2"
loopbacks:
  - id: 0
    address: "2.2.2.2/32"

underlay_interfaces:
  - id: "1/1"
    address: "10.0.14.1/31"
  - id: "1/2"
    address: "10.0.15.1/31"

vrfs:
  - name: "Tenant-A"
    l3_vni:
      vlan_id: 99
      vni: 10099
    vlans:
      - id: 10
        vni: 10010
        svi_address: "192.168.10.2/24"
    
access_interfaces:
  - id: "1/10"
    vlan_id: 10
