# hostname: "Leaf1"
# loopbacks:
#   - id: 0
#     address: "1.1.1.1/32"

# underlay_interfaces:
#   - id: "1/1"
#     address: "10.0.12.1/31"
#   - id: "1/2"
#     address: "10.0.13.1/31"

# vrfs:
#   - name: "Tenant-A"
#     l3_vni:
#       vlan_id: 99
#       vni: 10099
#     vlans:
#       - id: 10
#         vni: 10010
#         svi_address: "192.168.10.1/24"
#   - name: "Tenant-B"
#     l3_vni:
#       vlan_id: 100
#       vni: 10100
#     vlans:
#       - id: 20
#         vni: 10020
#         svi_address: "192.168.20.1/24"

# access_interfaces:
#   - id: "1/10"
#     vlan_id: 10
#   - id: "1/11"
#     vlan_id: 20
