hostname: "Spine2"
loopbacks:
  - id: 0
    address: "4.4.4.4/32"

underlay_interfaces:
  - id: "1/1"
    address: "10.0.13.0/31"
  - id: "1/2"
    address: "10.0.15.0/31"
  - id: "1/49"
    address: "10.0.2.2/24"

default_gateway: "10.0.2.1"